Multiple images for eval.run_llava
haotian-liu/LLaVA pull request #432
Opened 2023-09-12 02:50 UTC by HireTheHero

PR for #57 and #197.
In case of multiple images, `eval.run_llava` with this PR could handle with arguments like below.
```
# example for two images
python -m llava.eval.run_llava \
    --model-path <model-path> \
    --image-file <image1-path><separator><image2-path> \
    --sep <separator> \
    --query "text <image-placeholder> text <image-placeholder> text"
```
My formatter added some additional changes, edit it if you'd like.

2023-10-12 23:02 UTC, haotian-liu requested changes
Thank you for the great work, and sorry for the late response (for some reason this PR does not appear in my inbox).

Having multiple image support would be definitely beneficial. Left some comments in the code that we can discuss.

Also, do you have any examples of the model inference results so that we can just get a sense of how the model is performing. Thanks.

2023-10-12 23:02 UTC, haotian-liu commented on llava/eval/run_llava.py
> +    if type(image_files) is list:
maybe redundant IFs, see above

2023-10-12 23:02 UTC, haotian-liu commented on llava/eval/run_llava.py
> +    if args.sep in args.image_file:
these IFs that use two pipelines for processing single-image and multiple image conversation, seems unnecessary as the single image is just a special case of the multiple images, and "<img_path>".split("") will just return a list that has a single element, no?

2023-10-14 10:27 UTC, HireTheHero commented on llava/eval/run_llava.py
> +    parser.add_argument("--sep", type=str, default="__sepsep__")
Was easy for me to debug but I guess you're right. 
Now it should look like: `parser.add_argument("--sep", type=str, default=",")`

2023-10-14 10:32 UTC, HireTheHero commented on llava/eval/run_llava.py
> +    if type(image_files) is list:
Removed if condition to return list anyway

2023-10-14 10:33 UTC, HireTheHero commented on llava/eval/run_llava.py
> +    if args.sep in args.image_file:
Now it's like this:
```
def load_images(image_files):
    out = []
    for image_file in image_files:
        image = load_image(image_file)
        out.append(image)
    return out
```

2023-10-14 14:03 UTC, HireTheHero commented
@haotian-liu Thank you for your feedback. Requested changes should be reflected on the up2date version.

I found some good-looking example, but is too task-specific to show here.
As for general multiple-image comprehension, I admit it's quite yet-to-be-improved like this
![multiple image example](https://github.com/haotian-liu/LLaVA/assets/65780758/d1009647-f595-47f7-b384-9c9f9d77cbd5)
(although I can see the model is trying to describe the second image, I also can see it's mixed)

For full notebook outputs, please see [here](https://github.com/HireTheHero/Machine_Notebooks/blob/main/LLaVA_multiple_image.ipynb).
For some reason you added ipynb to .gitignore, so I've temporarily added to my own repo.

I guess we have three options-
1. Pend this feature until any of us can get a good example
    - I wouldn't choose this since many users seem to be interested (maybe someone can find a good example later to show here? but it's your choice, of course)
3. Add this as nightly feature
    - Maybe reasonable. If you agree, I will rename PR's title like `[Nightly] Multiple images for eval.run_llava`
4. More investigation
    - If you have some ideas for the quick improvement (e.g. preprocessing step should be divided for multiple images), I can test it

What do you think?

2023-10-21 06:56 UTC, HireTheHero commented
@haotian-liu Maybe LLaVA 1.5 can handle it with a one-to-one fashion prompt?
![image](https://github.com/haotian-liu/LLaVA/assets/65780758/12c089c9-9435-44ae-952e-db58289243b0)
Full output: 
`The image features a red toy animal, possibly a toy horse, with flames coming out of its back. The toy is placed on a surface, possibly a table, and is wearing glasses. The overall appearance of the toy is unique and eye-catching, with the combination of the red color, flames, and glasses creating a distinctive and interesting visual effect.`

2023-11-04 19:27 UTC, haotian-liu approved these changes

2023-11-04 19:29 UTC, merged

2023-11-04 19:29 UTC, haotian-liu commented
Thank you!

2023-11-05 01:33 UTC, shure-dev commented
Hi, thank you for your work including the code update
In conclusion, do we have to wait for multi-image support until the next pre-trained model comes up?

2023-11-05 09:05 UTC, HireTheHero commented
@shure-dev 
The example above says LLaVA 1.5 `liuhaotian/llava-v1.5-13b` might work. Appreciate it if you would test more.

2023-11-06 00:29 UTC, shure-dev commented
@HireTheHero @haotian-liu 
Thank you 
I'm having my experiment now with a quantized model from here https://huggingface.co/4bit
but it's not working well, the model tries to recognize only the first image.

Also, I found that, in the Gradio web interface, every time I upload a second image, it clears all chat history. 
Do you know about this?

2023-11-06 05:00 UTC, HireTheHero commented
@shure-dev Thanks for letting know of your findings. Am also personally working on LoRA/QLoRA - will keep you posted.
@haotian-liu Do you have any ideas about Gradio issue? Never used myself

2023-11-06 06:11 UTC, shure-dev commented
Thank you for your support. I appreciate it.

I'm also wondering if it is possible for the LLaVA model to understand multiple images separately at once if we think of its architecture. Specifically, how does the model know that "first image" (text) is related to "first image" (actual image) and "second image" (text) is related to "second image" (actual image)?

2023-11-25 05:43 UTC, HireTheHero commented
@shure-dev 
Apologies for the late response. That's an interesting question.
My example doesn't use the text "1st" or "2nd", and it gives the two images in separate user-agent interaction, I'm not sure about the model comprehension.
Maybe the model learns one-to-one text-image mapping during contrastive training, while it grasps the meaning of "first" and "second" during language training, but needs careful prompt design to test it since one-shot representation didn't work.